import { Course, Question, ExamResult, ExamSession } from '../types';

export const mockCourses: Course[] = [
  {
    id: 'course-1',
    title: 'Calculus I: Limits and Derivatives',
    subject: 'Mathematics',
    language: 'en',
    tags: ['calculus', 'derivatives', 'limits', 'mathematics'],
    shortDesc: 'Master the fundamentals of differential calculus including limits, continuity, and derivatives.',
    progressPercent: 65,
    difficultyTag: 'medium',
    stages: [
      { id: 's1-1', title: 'Introduction to Limits', order: 1, estimatedDurationMinutes: 30, contentRef: 'content/calc1/limits-intro', locked: false },
      { id: 's1-2', title: 'Computing Limits Algebraically', order: 2, estimatedDurationMinutes: 45, contentRef: 'content/calc1/limits-algebra', locked: false },
      { id: 's1-3', title: 'Continuity and Discontinuity', order: 3, estimatedDurationMinutes: 40, contentRef: 'content/calc1/continuity', locked: false },
      { id: 's1-4', title: 'Definition of the Derivative', order: 4, estimatedDurationMinutes: 50, contentRef: 'content/calc1/derivative-def', locked: false },
      { id: 's1-5', title: 'Differentiation Rules', order: 5, estimatedDurationMinutes: 60, contentRef: 'content/calc1/diff-rules', locked: true },
      { id: 's1-6', title: 'Chain Rule and Implicit Differentiation', order: 6, estimatedDurationMinutes: 55, contentRef: 'content/calc1/chain-rule', locked: true },
    ],
  },
  {
    id: 'course-2',
    title: 'Classical Mechanics',
    subject: 'Physics',
    language: 'en',
    tags: ['mechanics', 'newton', 'kinematics', 'physics'],
    shortDesc: "Explore Newton's laws, energy, momentum, and the mechanics of motion.",
    progressPercent: 30,
    difficultyTag: 'hard',
    stages: [
      { id: 's2-1', title: "Newton's Laws of Motion", order: 1, estimatedDurationMinutes: 45, contentRef: 'content/phys/newton-laws', locked: false },
      { id: 's2-2', title: 'Kinematics in 1D', order: 2, estimatedDurationMinutes: 40, contentRef: 'content/phys/kinematics-1d', locked: false },
      { id: 's2-3', title: 'Kinematics in 2D and Projectile Motion', order: 3, estimatedDurationMinutes: 50, contentRef: 'content/phys/kinematics-2d', locked: false },
      { id: 's2-4', title: 'Work, Energy, and Power', order: 4, estimatedDurationMinutes: 55, contentRef: 'content/phys/energy', locked: true },
      { id: 's2-5', title: 'Conservation of Momentum', order: 5, estimatedDurationMinutes: 50, contentRef: 'content/phys/momentum', locked: true },
    ],
  },
  {
    id: 'course-3',
    title: 'Introduction to Algorithms',
    subject: 'Computer Science',
    language: 'en',
    tags: ['algorithms', 'data-structures', 'complexity', 'programming'],
    shortDesc: 'Learn algorithmic thinking, sorting, searching, and time complexity analysis.',
    progressPercent: 80,
    difficultyTag: 'medium',
    stages: [
      { id: 's3-1', title: 'Big O Notation and Complexity', order: 1, estimatedDurationMinutes: 35, contentRef: 'content/cs/big-o', locked: false },
      { id: 's3-2', title: 'Arrays and Linked Lists', order: 2, estimatedDurationMinutes: 40, contentRef: 'content/cs/arrays-lists', locked: false },
      { id: 's3-3', title: 'Sorting Algorithms', order: 3, estimatedDurationMinutes: 60, contentRef: 'content/cs/sorting', locked: false },
      { id: 's3-4', title: 'Binary Search and Search Trees', order: 4, estimatedDurationMinutes: 50, contentRef: 'content/cs/search', locked: false },
      { id: 's3-5', title: 'Graphs and BFS/DFS', order: 5, estimatedDurationMinutes: 65, contentRef: 'content/cs/graphs', locked: true },
    ],
  },
  {
    id: 'course-4',
    title: 'World Literature: Modernism to Postmodernism',
    subject: 'Literature',
    language: 'en',
    tags: ['literature', 'modernism', 'postmodernism', 'novels'],
    shortDesc: 'Analyse landmark works from Joyce, Kafka, Woolf, and Pynchon through a critical lens.',
    progressPercent: 0,
    difficultyTag: 'easy',
    stages: [
      { id: 's4-1', title: 'The Modernist Movement', order: 1, estimatedDurationMinutes: 30, contentRef: 'content/lit/modernism', locked: false },
      { id: 's4-2', title: "Virginia Woolf's Mrs. Dalloway", order: 2, estimatedDurationMinutes: 45, contentRef: 'content/lit/woolf', locked: false },
      { id: 's4-3', title: "Kafka's The Trial", order: 3, estimatedDurationMinutes: 40, contentRef: 'content/lit/kafka', locked: true },
      { id: 's4-4', title: 'Postmodern Narrative Techniques', order: 4, estimatedDurationMinutes: 35, contentRef: 'content/lit/postmodern', locked: true },
    ],
  },
  {
    id: 'course-5',
    title: 'Modern World History: 1900–2000',
    subject: 'History',
    language: 'en',
    tags: ['history', 'world-war', 'cold-war', 'modern'],
    shortDesc: 'A comprehensive survey of 20th-century global history from WWI to the fall of the Soviet Union.',
    progressPercent: 45,
    difficultyTag: 'easy',
    stages: [
      { id: 's5-1', title: 'Causes of World War I', order: 1, estimatedDurationMinutes: 35, contentRef: 'content/hist/wwi-causes', locked: false },
      { id: 's5-2', title: 'The Interwar Period', order: 2, estimatedDurationMinutes: 40, contentRef: 'content/hist/interwar', locked: false },
      { id: 's5-3', title: 'World War II and the Holocaust', order: 3, estimatedDurationMinutes: 55, contentRef: 'content/hist/wwii', locked: false },
      { id: 's5-4', title: 'The Cold War', order: 4, estimatedDurationMinutes: 50, contentRef: 'content/hist/cold-war', locked: true },
      { id: 's5-5', title: 'Decolonization and Independence Movements', order: 5, estimatedDurationMinutes: 45, contentRef: 'content/hist/decolonization', locked: true },
      { id: 's5-6', title: 'The Fall of the Berlin Wall', order: 6, estimatedDurationMinutes: 30, contentRef: 'content/hist/berlin-wall', locked: true },
    ],
  },
  {
    id: 'course-6',
    title: 'Microeconomics: Markets and Decisions',
    subject: 'Economics',
    language: 'en',
    tags: ['economics', 'microeconomics', 'supply-demand', 'markets'],
    shortDesc: 'Understand how individuals and firms make decisions, and how markets coordinate economic activity.',
    progressPercent: 20,
    difficultyTag: 'medium',
    stages: [
      { id: 's6-1', title: 'Supply and Demand', order: 1, estimatedDurationMinutes: 40, contentRef: 'content/econ/supply-demand', locked: false },
      { id: 's6-2', title: 'Elasticity', order: 2, estimatedDurationMinutes: 35, contentRef: 'content/econ/elasticity', locked: false },
      { id: 's6-3', title: 'Consumer Theory', order: 3, estimatedDurationMinutes: 50, contentRef: 'content/econ/consumer-theory', locked: false },
      { id: 's6-4', title: 'Production and Costs', order: 4, estimatedDurationMinutes: 45, contentRef: 'content/econ/production', locked: true },
      { id: 's6-5', title: 'Market Structures', order: 5, estimatedDurationMinutes: 55, contentRef: 'content/econ/market-structures', locked: true },
    ],
  },
];

export const mockQuestions: Question[] = [
  {
    id: 'q1',
    text: 'What is the limit of sin(x)/x as x approaches 0?',
    options: ['0', '1', 'undefined', 'infinity'],
    correct: '1',
    type: 'single',
    difficulty: 'easy',
    tags: ['calculus', 'limits', 'trigonometry'],
    explanation: 'By the fundamental trigonometric limit, lim(x→0) sin(x)/x = 1. This can be proven geometrically or using L\'Hôpital\'s rule.',
    trick: 'This is one of the most important limits in calculus — memorize it!',
  },
  {
    id: 'q2',
    text: 'Which of the following are applications of the derivative? (Select all that apply)',
    options: ['Finding slope of a tangent line', 'Computing area under a curve', 'Optimizing functions', 'Finding rates of change'],
    correct: ['Finding slope of a tangent line', 'Optimizing functions', 'Finding rates of change'],
    type: 'multi',
    difficulty: 'medium',
    tags: ['calculus', 'derivatives', 'applications'],
    explanation: 'Derivatives measure instantaneous rates of change and slopes of tangent lines. Area under a curve is computed using integrals (antiderivatives), not derivatives.',
  },
  {
    id: 'q3',
    text: "A car accelerates from rest at 5 m/s². How far does it travel in 4 seconds?",
    options: ['20 m', '40 m', '80 m', '10 m'],
    correct: '40 m',
    type: 'single',
    difficulty: 'medium',
    tags: ['physics', 'kinematics', 'acceleration'],
    explanation: 'Using s = ½at²: s = ½ × 5 × 4² = ½ × 5 × 16 = 40 m.',
    trick: 'Remember the kinematic equation s = ut + ½at². With u=0 (starts from rest), it simplifies to s = ½at².',
  },
  {
    id: 'q4',
    text: "What is the time complexity of binary search on a sorted array?",
    options: ['O(n)', 'O(log n)', 'O(n log n)', 'O(1)'],
    correct: 'O(log n)',
    type: 'single',
    difficulty: 'easy',
    tags: ['computer-science', 'algorithms', 'complexity'],
    explanation: 'Binary search halves the search space with each comparison, resulting in O(log n) time complexity where n is the array length.',
  },
  {
    id: 'q5',
    text: "Which literary technique does Virginia Woolf primarily use in Mrs. Dalloway?",
    options: ['Third-person omniscient narration', 'Stream of consciousness', 'Epistolary form', 'Unreliable narrator'],
    correct: 'Stream of consciousness',
    type: 'single',
    difficulty: 'easy',
    tags: ['literature', 'modernism', 'woolf'],
    explanation: "Woolf pioneered the stream of consciousness technique, directly representing a character's inner thoughts and perceptions as they flow naturally through the mind.",
  },
  {
    id: 'q6',
    text: 'What event directly triggered the start of World War I?',
    options: ['The invasion of Poland', 'The assassination of Archduke Franz Ferdinand', 'The sinking of the Lusitania', 'The signing of the Treaty of Versailles'],
    correct: 'The assassination of Archduke Franz Ferdinand',
    type: 'single',
    difficulty: 'easy',
    tags: ['history', 'wwi', 'causes'],
    explanation: 'The assassination of Archduke Franz Ferdinand of Austria-Hungary in Sarajevo on June 28, 1914, triggered a chain of events that led to World War I.',
  },
  {
    id: 'q7',
    text: 'If the price of a good rises and the quantity demanded falls, the demand curve is:',
    options: ['Upward sloping', 'Downward sloping', 'Horizontal', 'Vertical'],
    correct: 'Downward sloping',
    type: 'single',
    difficulty: 'easy',
    tags: ['economics', 'microeconomics', 'demand'],
    explanation: 'The law of demand states that as price increases, quantity demanded decreases, resulting in a downward-sloping demand curve.',
  },
  {
    id: 'q8',
    text: "What is the derivative of f(x) = x³ + 2x² - 5x + 7?",
    options: ['3x² + 4x - 5', '3x² + 2x - 5', 'x² + 4x - 5', '3x³ + 4x² - 5'],
    correct: '3x² + 4x - 5',
    type: 'single',
    difficulty: 'medium',
    tags: ['calculus', 'derivatives', 'polynomial'],
    explanation: 'Applying the power rule: d/dx(x³) = 3x², d/dx(2x²) = 4x, d/dx(-5x) = -5, d/dx(7) = 0. So f\'(x) = 3x² + 4x - 5.',
  },
  {
    id: 'q9',
    text: 'Which of the following sorting algorithms have O(n log n) average-case complexity? (Select all)',
    options: ['Bubble Sort', 'Merge Sort', 'Quick Sort', 'Insertion Sort'],
    correct: ['Merge Sort', 'Quick Sort'],
    type: 'multi',
    difficulty: 'medium',
    tags: ['computer-science', 'sorting', 'complexity'],
    explanation: 'Merge Sort always runs in O(n log n). Quick Sort has O(n log n) average case but O(n²) worst case. Bubble Sort and Insertion Sort are O(n²) on average.',
  },
  {
    id: 'q10',
    text: "Newton's second law states F = ma. If a force of 20 N acts on a 4 kg object, what is its acceleration?",
    options: ['80 m/s²', '5 m/s²', '16 m/s²', '0.2 m/s²'],
    correct: '5 m/s²',
    type: 'single',
    difficulty: 'easy',
    tags: ['physics', 'newton', 'force'],
    explanation: 'From F = ma, we get a = F/m = 20/4 = 5 m/s².',
  },
  {
    id: 'q11',
    text: 'The Cold War was primarily a conflict between which two superpowers?',
    options: ['USA and China', 'USA and USSR', 'UK and USSR', 'USA and Germany'],
    correct: 'USA and USSR',
    type: 'single',
    difficulty: 'easy',
    tags: ['history', 'cold-war', '20th-century'],
    explanation: 'The Cold War (1947–1991) was a geopolitical and ideological conflict between the United States and the Soviet Union (USSR).',
  },
  {
    id: 'q12',
    text: 'Price elasticity of demand measures:',
    options: [
      'How quantity supplied responds to price changes',
      'How quantity demanded responds to income changes',
      'How quantity demanded responds to price changes',
      'How price responds to supply changes',
    ],
    correct: 'How quantity demanded responds to price changes',
    type: 'single',
    difficulty: 'medium',
    tags: ['economics', 'elasticity', 'demand'],
    explanation: 'Price elasticity of demand (PED) = % change in quantity demanded / % change in price. It measures the sensitivity of consumer demand to price changes.',
  },
  {
    id: 'q13',
    text: 'What does Big O notation describe?',
    options: ['The exact runtime of an algorithm', 'The upper bound of an algorithm\'s growth rate', 'The average case performance', 'The memory usage only'],
    correct: 'The upper bound of an algorithm\'s growth rate',
    type: 'single',
    difficulty: 'easy',
    tags: ['computer-science', 'big-o', 'complexity'],
    explanation: 'Big O notation describes the upper bound (worst case) of an algorithm\'s time or space complexity as input size grows towards infinity.',
  },
  {
    id: 'q14',
    text: 'Which of the following are properties of a perfectly competitive market? (Select all)',
    options: ['Many buyers and sellers', 'Homogeneous products', 'Price-setting power by firms', 'Free entry and exit'],
    correct: ['Many buyers and sellers', 'Homogeneous products', 'Free entry and exit'],
    type: 'multi',
    difficulty: 'hard',
    tags: ['economics', 'market-structures', 'competition'],
    explanation: 'Perfect competition is characterized by many buyers/sellers, identical (homogeneous) products, and free entry/exit. Firms are price takers, not price setters.',
  },
  {
    id: 'q15',
    text: "Which postmodern technique involves a narrative that is aware of its own fictional nature?",
    options: ['Magical realism', 'Metafiction', 'Stream of consciousness', 'Epistolary narration'],
    correct: 'Metafiction',
    type: 'single',
    difficulty: 'hard',
    tags: ['literature', 'postmodernism', 'narrative'],
    explanation: 'Metafiction is a form of narrative that self-consciously addresses the devices of fiction, calling attention to its status as an artifact and questioning the relationship between fiction and reality.',
  },
];

export const mockExamResults: ExamResult[] = [
  {
    id: 'result-1',
    userId: '1',
    examId: 'exam-calc-1',
    score: 78,
    accuracy: 0.78,
    timeTakenSeconds: 2340,
    topicBreakdown: { 'Limits': 90, 'Derivatives': 75, 'Continuity': 70 },
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'result-2',
    userId: '1',
    examId: 'exam-physics-1',
    score: 65,
    accuracy: 0.65,
    timeTakenSeconds: 3600,
    topicBreakdown: { 'Kinematics': 80, 'Newton\'s Laws': 60, 'Energy': 55 },
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: 'result-3',
    userId: '1',
    examId: 'exam-cs-1',
    score: 92,
    accuracy: 0.92,
    timeTakenSeconds: 1800,
    topicBreakdown: { 'Big O Notation': 100, 'Sorting': 90, 'Search': 85 },
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
];

export const mockExamSession: ExamSession = {
  sessionId: 'session-demo-1',
  examId: 'exam-mixed-1',
  questions: mockQuestions.slice(0, 5),
  startedAt: new Date().toISOString(),
  answers: {},
  flagged: [],
};
