import { type Course, type Question, type ExamResult, type ExamSession, type ExamCard, type ResourceLink } from '../types';

export const mockCourses: Course[] = [
  {
    id: 'course-1',
    title: 'Calculus I: Limits and Derivatives',
    subject: 'Mathematics',
    language: 'en',
    tags: ['calculus', 'derivatives', 'limits', 'mathematics'],
    shortDesc: 'Master the fundamentals of differential calculus including limits, continuity, and derivatives.',
    progressPercent: 65,
    difficultyTag: 'medium',
    stages: [
      { id: 's1-1', title: 'Introduction to Limits', order: 1, estimatedDurationMinutes: 30, contentRef: 'content/calc1/limits-intro', locked: false },
      { id: 's1-2', title: 'Computing Limits Algebraically', order: 2, estimatedDurationMinutes: 45, contentRef: 'content/calc1/limits-algebra', locked: false },
      { id: 's1-3', title: 'Continuity and Discontinuity', order: 3, estimatedDurationMinutes: 40, contentRef: 'content/calc1/continuity', locked: false },
      { id: 's1-4', title: 'Definition of the Derivative', order: 4, estimatedDurationMinutes: 50, contentRef: 'content/calc1/derivative-def', locked: false },
      { id: 's1-5', title: 'Differentiation Rules', order: 5, estimatedDurationMinutes: 60, contentRef: 'content/calc1/diff-rules', locked: true },
      { id: 's1-6', title: 'Chain Rule and Implicit Differentiation', order: 6, estimatedDurationMinutes: 55, contentRef: 'content/calc1/chain-rule', locked: true },
    ],
  },
  {
    id: 'course-2',
    title: 'Classical Mechanics',
    subject: 'Physics',
    language: 'en',
    tags: ['mechanics', 'newton', 'kinematics', 'physics'],
    shortDesc: "Explore Newton's laws, energy, momentum, and the mechanics of motion.",
    progressPercent: 30,
    difficultyTag: 'hard',
    stages: [
      { id: 's2-1', title: "Newton's Laws of Motion", order: 1, estimatedDurationMinutes: 45, contentRef: 'content/phys/newton-laws', locked: false },
      { id: 's2-2', title: 'Kinematics in 1D', order: 2, estimatedDurationMinutes: 40, contentRef: 'content/phys/kinematics-1d', locked: false },
      { id: 's2-3', title: 'Kinematics in 2D and Projectile Motion', order: 3, estimatedDurationMinutes: 50, contentRef: 'content/phys/kinematics-2d', locked: false },
      { id: 's2-4', title: 'Work, Energy, and Power', order: 4, estimatedDurationMinutes: 55, contentRef: 'content/phys/energy', locked: true },
      { id: 's2-5', title: 'Conservation of Momentum', order: 5, estimatedDurationMinutes: 50, contentRef: 'content/phys/momentum', locked: true },
    ],
  },
  {
    id: 'course-3',
    title: 'Introduction to Algorithms',
    subject: 'Computer Science',
    language: 'en',
    tags: ['algorithms', 'data-structures', 'complexity', 'programming'],
    shortDesc: 'Learn algorithmic thinking, sorting, searching, and time complexity analysis.',
    progressPercent: 80,
    difficultyTag: 'medium',
    stages: [
      { id: 's3-1', title: 'Big O Notation and Complexity', order: 1, estimatedDurationMinutes: 35, contentRef: 'content/cs/big-o', locked: false },
      { id: 's3-2', title: 'Arrays and Linked Lists', order: 2, estimatedDurationMinutes: 40, contentRef: 'content/cs/arrays-lists', locked: false },
      { id: 's3-3', title: 'Sorting Algorithms', order: 3, estimatedDurationMinutes: 60, contentRef: 'content/cs/sorting', locked: false },
      { id: 's3-4', title: 'Binary Search and Search Trees', order: 4, estimatedDurationMinutes: 50, contentRef: 'content/cs/search', locked: false },
      { id: 's3-5', title: 'Graphs and BFS/DFS', order: 5, estimatedDurationMinutes: 65, contentRef: 'content/cs/graphs', locked: true },
    ],
  },
  {
    id: 'course-4',
    title: 'World Literature: Modernism to Postmodernism',
    subject: 'Literature',
    language: 'en',
    tags: ['literature', 'modernism', 'postmodernism', 'novels'],
    shortDesc: 'Analyse landmark works from Joyce, Kafka, Woolf, and Pynchon through a critical lens.',
    progressPercent: 0,
    difficultyTag: 'easy',
    stages: [
      { id: 's4-1', title: 'The Modernist Movement', order: 1, estimatedDurationMinutes: 30, contentRef: 'content/lit/modernism', locked: false },
      { id: 's4-2', title: "Virginia Woolf's Mrs. Dalloway", order: 2, estimatedDurationMinutes: 45, contentRef: 'content/lit/woolf', locked: false },
      { id: 's4-3', title: "Kafka's The Trial", order: 3, estimatedDurationMinutes: 40, contentRef: 'content/lit/kafka', locked: true },
      { id: 's4-4', title: 'Postmodern Narrative Techniques', order: 4, estimatedDurationMinutes: 35, contentRef: 'content/lit/postmodern', locked: true },
    ],
  },
  {
    id: 'course-5',
    title: 'Modern World History: 1900–2000',
    subject: 'History',
    language: 'en',
    tags: ['history', 'world-war', 'cold-war', 'modern'],
    shortDesc: 'A comprehensive survey of 20th-century global history from WWI to the fall of the Soviet Union.',
    progressPercent: 45,
    difficultyTag: 'easy',
    stages: [
      { id: 's5-1', title: 'Causes of World War I', order: 1, estimatedDurationMinutes: 35, contentRef: 'content/hist/wwi-causes', locked: false },
      { id: 's5-2', title: 'The Interwar Period', order: 2, estimatedDurationMinutes: 40, contentRef: 'content/hist/interwar', locked: false },
      { id: 's5-3', title: 'World War II and the Holocaust', order: 3, estimatedDurationMinutes: 55, contentRef: 'content/hist/wwii', locked: false },
      { id: 's5-4', title: 'The Cold War', order: 4, estimatedDurationMinutes: 50, contentRef: 'content/hist/cold-war', locked: true },
      { id: 's5-5', title: 'Decolonization and Independence Movements', order: 5, estimatedDurationMinutes: 45, contentRef: 'content/hist/decolonization', locked: true },
      { id: 's5-6', title: 'The Fall of the Berlin Wall', order: 6, estimatedDurationMinutes: 30, contentRef: 'content/hist/berlin-wall', locked: true },
    ],
  },
  {
    id: 'course-6',
    title: 'Microeconomics: Markets and Decisions',
    subject: 'Economics',
    language: 'en',
    tags: ['economics', 'microeconomics', 'supply-demand', 'markets'],
    shortDesc: 'Understand how individuals and firms make decisions, and how markets coordinate economic activity.',
    progressPercent: 20,
    difficultyTag: 'medium',
    stages: [
      { id: 's6-1', title: 'Supply and Demand', order: 1, estimatedDurationMinutes: 40, contentRef: 'content/econ/supply-demand', locked: false },
      { id: 's6-2', title: 'Elasticity', order: 2, estimatedDurationMinutes: 35, contentRef: 'content/econ/elasticity', locked: false },
      { id: 's6-3', title: 'Consumer Theory', order: 3, estimatedDurationMinutes: 50, contentRef: 'content/econ/consumer-theory', locked: false },
      { id: 's6-4', title: 'Production and Costs', order: 4, estimatedDurationMinutes: 45, contentRef: 'content/econ/production', locked: true },
      { id: 's6-5', title: 'Market Structures', order: 5, estimatedDurationMinutes: 55, contentRef: 'content/econ/market-structures', locked: true },
    ],
  },
];

export const mockQuestions: Question[] = [
  {
    id: 'q1',
    text: 'What is the limit of sin(x)/x as x approaches 0?',
    options: ['0', '1', 'undefined', 'infinity'],
    correct: '1',
    type: 'single',
    difficulty: 'easy',
    tags: ['calculus', 'limits', 'trigonometry'],
    explanation: 'By the fundamental trigonometric limit, lim(x→0) sin(x)/x = 1. This can be proven geometrically or using L\'Hôpital\'s rule.',
    trick: 'This is one of the most important limits in calculus — memorize it!',
  },
  {
    id: 'q2',
    text: 'Which of the following are applications of the derivative? (Select all that apply)',
    options: ['Finding slope of a tangent line', 'Computing area under a curve', 'Optimizing functions', 'Finding rates of change'],
    correct: ['Finding slope of a tangent line', 'Optimizing functions', 'Finding rates of change'],
    type: 'multi',
    difficulty: 'medium',
    tags: ['calculus', 'derivatives', 'applications'],
    explanation: 'Derivatives measure instantaneous rates of change and slopes of tangent lines. Area under a curve is computed using integrals (antiderivatives), not derivatives.',
  },
  {
    id: 'q3',
    text: "A car accelerates from rest at 5 m/s². How far does it travel in 4 seconds?",
    options: ['20 m', '40 m', '80 m', '10 m'],
    correct: '40 m',
    type: 'single',
    difficulty: 'medium',
    tags: ['physics', 'kinematics', 'acceleration'],
    explanation: 'Using s = ½at²: s = ½ × 5 × 4² = ½ × 5 × 16 = 40 m.',
    trick: 'Remember the kinematic equation s = ut + ½at². With u=0 (starts from rest), it simplifies to s = ½at².',
  },
  {
    id: 'q4',
    text: "What is the time complexity of binary search on a sorted array?",
    options: ['O(n)', 'O(log n)', 'O(n log n)', 'O(1)'],
    correct: 'O(log n)',
    type: 'single',
    difficulty: 'easy',
    tags: ['computer-science', 'algorithms', 'complexity'],
    explanation: 'Binary search halves the search space with each comparison, resulting in O(log n) time complexity where n is the array length.',
  },
  {
    id: 'q5',
    text: "Which literary technique does Virginia Woolf primarily use in Mrs. Dalloway?",
    options: ['Third-person omniscient narration', 'Stream of consciousness', 'Epistolary form', 'Unreliable narrator'],
    correct: 'Stream of consciousness',
    type: 'single',
    difficulty: 'easy',
    tags: ['literature', 'modernism', 'woolf'],
    explanation: "Woolf pioneered the stream of consciousness technique, directly representing a character's inner thoughts and perceptions as they flow naturally through the mind.",
  },
  {
    id: 'q6',
    text: 'What event directly triggered the start of World War I?',
    options: ['The invasion of Poland', 'The assassination of Archduke Franz Ferdinand', 'The sinking of the Lusitania', 'The signing of the Treaty of Versailles'],
    correct: 'The assassination of Archduke Franz Ferdinand',
    type: 'single',
    difficulty: 'easy',
    tags: ['history', 'wwi', 'causes'],
    explanation: 'The assassination of Archduke Franz Ferdinand of Austria-Hungary in Sarajevo on June 28, 1914, triggered a chain of events that led to World War I.',
  },
  {
    id: 'q7',
    text: 'If the price of a good rises and the quantity demanded falls, the demand curve is:',
    options: ['Upward sloping', 'Downward sloping', 'Horizontal', 'Vertical'],
    correct: 'Downward sloping',
    type: 'single',
    difficulty: 'easy',
    tags: ['economics', 'microeconomics', 'demand'],
    explanation: 'The law of demand states that as price increases, quantity demanded decreases, resulting in a downward-sloping demand curve.',
  },
  {
    id: 'q8',
    text: "What is the derivative of f(x) = x³ + 2x² - 5x + 7?",
    options: ['3x² + 4x - 5', '3x² + 2x - 5', 'x² + 4x - 5', '3x³ + 4x² - 5'],
    correct: '3x² + 4x - 5',
    type: 'single',
    difficulty: 'medium',
    tags: ['calculus', 'derivatives', 'polynomial'],
    explanation: 'Applying the power rule: d/dx(x³) = 3x², d/dx(2x²) = 4x, d/dx(-5x) = -5, d/dx(7) = 0. So f\'(x) = 3x² + 4x - 5.',
  },
  {
    id: 'q9',
    text: 'Which of the following sorting algorithms have O(n log n) average-case complexity? (Select all)',
    options: ['Bubble Sort', 'Merge Sort', 'Quick Sort', 'Insertion Sort'],
    correct: ['Merge Sort', 'Quick Sort'],
    type: 'multi',
    difficulty: 'medium',
    tags: ['computer-science', 'sorting', 'complexity'],
    explanation: 'Merge Sort always runs in O(n log n). Quick Sort has O(n log n) average case but O(n²) worst case. Bubble Sort and Insertion Sort are O(n²) on average.',
  },
  {
    id: 'q10',
    text: "Newton's second law states F = ma. If a force of 20 N acts on a 4 kg object, what is its acceleration?",
    options: ['80 m/s²', '5 m/s²', '16 m/s²', '0.2 m/s²'],
    correct: '5 m/s²',
    type: 'single',
    difficulty: 'easy',
    tags: ['physics', 'newton', 'force'],
    explanation: 'From F = ma, we get a = F/m = 20/4 = 5 m/s².',
  },
  {
    id: 'q11',
    text: 'The Cold War was primarily a conflict between which two superpowers?',
    options: ['USA and China', 'USA and USSR', 'UK and USSR', 'USA and Germany'],
    correct: 'USA and USSR',
    type: 'single',
    difficulty: 'easy',
    tags: ['history', 'cold-war', '20th-century'],
    explanation: 'The Cold War (1947–1991) was a geopolitical and ideological conflict between the United States and the Soviet Union (USSR).',
  },
  {
    id: 'q12',
    text: 'Price elasticity of demand measures:',
    options: [
      'How quantity supplied responds to price changes',
      'How quantity demanded responds to income changes',
      'How quantity demanded responds to price changes',
      'How price responds to supply changes',
    ],
    correct: 'How quantity demanded responds to price changes',
    type: 'single',
    difficulty: 'medium',
    tags: ['economics', 'elasticity', 'demand'],
    explanation: 'Price elasticity of demand (PED) = % change in quantity demanded / % change in price. It measures the sensitivity of consumer demand to price changes.',
  },
  {
    id: 'q13',
    text: 'What does Big O notation describe?',
    options: ['The exact runtime of an algorithm', 'The upper bound of an algorithm\'s growth rate', 'The average case performance', 'The memory usage only'],
    correct: 'The upper bound of an algorithm\'s growth rate',
    type: 'single',
    difficulty: 'easy',
    tags: ['computer-science', 'big-o', 'complexity'],
    explanation: 'Big O notation describes the upper bound (worst case) of an algorithm\'s time or space complexity as input size grows towards infinity.',
  },
  {
    id: 'q14',
    text: 'Which of the following are properties of a perfectly competitive market? (Select all)',
    options: ['Many buyers and sellers', 'Homogeneous products', 'Price-setting power by firms', 'Free entry and exit'],
    correct: ['Many buyers and sellers', 'Homogeneous products', 'Free entry and exit'],
    type: 'multi',
    difficulty: 'hard',
    tags: ['economics', 'market-structures', 'competition'],
    explanation: 'Perfect competition is characterized by many buyers/sellers, identical (homogeneous) products, and free entry/exit. Firms are price takers, not price setters.',
  },
  {
    id: 'q15',
    text: "Which postmodern technique involves a narrative that is aware of its own fictional nature?",
    options: ['Magical realism', 'Metafiction', 'Stream of consciousness', 'Epistolary narration'],
    correct: 'Metafiction',
    type: 'single',
    difficulty: 'hard',
    tags: ['literature', 'postmodernism', 'narrative'],
    explanation: 'Metafiction is a form of narrative that self-consciously addresses the devices of fiction, calling attention to its status as an artifact and questioning the relationship between fiction and reality.',
  },
];

export const mockExamResults: ExamResult[] = [
  {
    id: 'result-1',
    userId: '1',
    examId: 'exam-calc-1',
    score: 78,
    accuracy: 0.78,
    timeTakenSeconds: 2340,
    topicBreakdown: { 'Limits': 90, 'Derivatives': 75, 'Continuity': 70 },
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'result-2',
    userId: '1',
    examId: 'exam-physics-1',
    score: 65,
    accuracy: 0.65,
    timeTakenSeconds: 3600,
    topicBreakdown: { 'Kinematics': 80, 'Newton\'s Laws': 60, 'Energy': 55 },
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: 'result-3',
    userId: '1',
    examId: 'exam-cs-1',
    score: 92,
    accuracy: 0.92,
    timeTakenSeconds: 1800,
    topicBreakdown: { 'Big O Notation': 100, 'Sorting': 90, 'Search': 85 },
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
];

export const mockExamSession: ExamSession = {
  sessionId: 'session-demo-1',
  examId: 'exam-mixed-1',
  questions: mockQuestions.slice(0, 5),
  startedAt: new Date().toISOString(),
  answers: {},
  flagged: [],
};

// ─── Competitive Exam Question Banks ────────────────────────────────────────

export const upscQuestions: Question[] = [
  {
    id: 'upsc-1',
    text: 'Which Article of the Indian Constitution deals with the Right to Education?',
    options: ['Article 21', 'Article 21A', 'Article 45', 'Article 46'],
    correct: 'Article 21A',
    type: 'single',
    difficulty: 'easy',
    tags: ['upsc', 'polity', 'constitution', 'fundamental-rights'],
    explanation: 'Article 21A was inserted by the 86th Constitutional Amendment Act, 2002, making free and compulsory education for children aged 6–14 a Fundamental Right.',
    trick: 'Article 21 = Right to Life, Article 21A = Right to Education (added by 86th Amendment).',
  },
  {
    id: 'upsc-2',
    text: 'The Preamble of the Indian Constitution was amended by which Constitutional Amendment?',
    options: ['42nd Amendment', '44th Amendment', '52nd Amendment', '73rd Amendment'],
    correct: '42nd Amendment',
    type: 'single',
    difficulty: 'medium',
    tags: ['upsc', 'polity', 'constitution', 'preamble'],
    explanation: 'The 42nd Constitutional Amendment Act, 1976 added the words "Socialist," "Secular," and "Integrity" to the Preamble.',
  },
  {
    id: 'upsc-3',
    text: 'Which of the following rivers does NOT originate in India?',
    options: ['Ganga', 'Brahmaputra', 'Indus', 'Godavari'],
    correct: 'Indus',
    type: 'single',
    difficulty: 'medium',
    tags: ['upsc', 'geography', 'rivers'],
    explanation: 'The Indus river originates from the Tibetan Plateau near Lake Mansarovar in China (Tibet). The Ganga, Brahmaputra (Yarlung Tsangpo), and Godavari originate in India.',
    trick: 'Indus originates in Tibet (Sengge Zangbo source). Remember: IBSN – Indus, Brahmaputra sources are in Tibet/China.',
  },
  {
    id: 'upsc-4',
    text: 'The concept of Directive Principles of State Policy was borrowed from which country\'s constitution?',
    options: ['USA', 'UK', 'Ireland', 'Canada'],
    correct: 'Ireland',
    type: 'single',
    difficulty: 'easy',
    tags: ['upsc', 'polity', 'dpsp', 'constitution'],
    explanation: 'The Directive Principles of State Policy (Part IV, Articles 36–51) were inspired by the Irish Constitution (Bunreacht na hÉireann, 1937).',
  },
  {
    id: 'upsc-5',
    text: 'Which Mughal emperor built the Taj Mahal?',
    options: ['Akbar', 'Jahangir', 'Shah Jahan', 'Aurangzeb'],
    correct: 'Shah Jahan',
    type: 'single',
    difficulty: 'easy',
    tags: ['upsc', 'history', 'mughal', 'monuments'],
    explanation: 'Shah Jahan built the Taj Mahal in Agra between 1632 and 1653 as a mausoleum for his wife Mumtaz Mahal.',
  },
  {
    id: 'upsc-6',
    text: 'Which of the following is/are correctly matched? (Select all that apply)\nI. Chipko Movement – Uttarakhand\nII. Narmada Bachao Andolan – Gujarat & Madhya Pradesh\nIII. Silent Valley Movement – Kerala',
    options: ['I only', 'I and II only', 'II and III only', 'I, II and III'],
    correct: 'I, II and III',
    type: 'single',
    difficulty: 'hard',
    tags: ['upsc', 'environment', 'social-movements'],
    explanation: 'All three are correctly matched. Chipko (1973) – Uttarakhand tree-hugging movement; Narmada Bachao Andolan – against Sardar Sarovar Dam; Silent Valley – protected tropical rainforest in Kerala.',
  },
  {
    id: 'upsc-7',
    text: 'The term "Green GDP" refers to:',
    options: [
      'GDP calculated using only renewable energy sectors',
      'GDP adjusted for environmental degradation costs',
      'GDP of countries with high forest cover',
      'GDP calculated excluding fossil fuel industries',
    ],
    correct: 'GDP adjusted for environmental degradation costs',
    type: 'single',
    difficulty: 'hard',
    tags: ['upsc', 'economics', 'environment', 'gdp'],
    explanation: 'Green GDP (or Genuine Progress Indicator) adjusts the conventional GDP by subtracting the environmental costs of economic activities such as pollution, resource depletion, and ecosystem damage.',
  },
  {
    id: 'upsc-8',
    text: 'The Rowlatt Act of 1919 was opposed because it:',
    options: [
      'Imposed heavy taxes on Indian goods',
      'Allowed detention without trial',
      'Banned Indian National Congress',
      'Transferred all judicial powers to British officers',
    ],
    correct: 'Allowed detention without trial',
    type: 'single',
    difficulty: 'easy',
    tags: ['upsc', 'history', 'freedom-struggle', 'british-era'],
    explanation: 'The Rowlatt Act (Anarchical and Revolutionary Crimes Act, 1919) allowed the government to imprison any person without trial. Gandhi called for a nationwide hartal (strike) against it.',
    trick: 'Rowlatt = "No Daleel, No Wakeel, No Appeal" – No argument, No lawyer, No appeal.',
  },
  {
    id: 'upsc-9',
    text: 'Mission Karmayogi is related to which sector?',
    options: ['Agriculture', 'Civil Service Capacity Building', 'Urban Housing', 'Digital Infrastructure'],
    correct: 'Civil Service Capacity Building',
    type: 'single',
    difficulty: 'medium',
    tags: ['upsc', 'current-affairs', 'governance'],
    explanation: 'Mission Karmayogi (National Programme for Civil Services Capacity Building) was launched in 2020 to reform the capacity building of civil servants in India.',
  },
  {
    id: 'upsc-10',
    text: 'Which of the following is the correct order of water bodies from largest to smallest area?',
    options: [
      'Pacific Ocean > Atlantic Ocean > Indian Ocean > Arctic Ocean',
      'Pacific Ocean > Indian Ocean > Atlantic Ocean > Arctic Ocean',
      'Atlantic Ocean > Pacific Ocean > Indian Ocean > Arctic Ocean',
      'Pacific Ocean > Atlantic Ocean > Arctic Ocean > Indian Ocean',
    ],
    correct: 'Pacific Ocean > Atlantic Ocean > Indian Ocean > Arctic Ocean',
    type: 'single',
    difficulty: 'medium',
    tags: ['upsc', 'geography', 'oceans'],
    explanation: 'The correct order by area: Pacific (~165.2M km²) > Atlantic (~106.4M km²) > Indian (~70.5M km²) > Arctic (~14.0M km²).',
    trick: 'PAInA = Pacific, Atlantic, Indian, Arctic',
  },
];

export const sscQuestions: Question[] = [
  {
    id: 'ssc-1',
    text: 'If COMPUTER is coded as RFUVQNPC, how is PRINTER coded?',
    options: ['QSJOUFS', 'SFOUFSJ', 'QSJOUFQ', 'JOFSQSU'],
    correct: 'QSJOUFS',
    type: 'single',
    difficulty: 'medium',
    tags: ['ssc', 'reasoning', 'coding-decoding'],
    explanation: 'Each letter is shifted one position forward in the alphabet: P→Q, R→S, I→J, N→O, T→U, E→F, R→S = QSJOUFS.',
  },
  {
    id: 'ssc-2',
    text: 'A train 150 m long passes a pole in 15 seconds. What is the speed of the train?',
    options: ['10 m/s', '12 m/s', '15 m/s', '8 m/s'],
    correct: '10 m/s',
    type: 'single',
    difficulty: 'easy',
    tags: ['ssc', 'quantitative-aptitude', 'time-speed-distance'],
    explanation: 'Speed = Distance / Time = 150 / 15 = 10 m/s.',
  },
  {
    id: 'ssc-3',
    text: 'Find the odd one out: 2, 5, 10, 17, 26, 37, 51',
    options: ['26', '37', '51', '17'],
    correct: '51',
    type: 'single',
    difficulty: 'medium',
    tags: ['ssc', 'reasoning', 'number-series'],
    explanation: 'The pattern is n² + 1: 1²+1=2, 2²+1=5, 3²+1=10, 4²+1=17, 5²+1=26, 6²+1=37, 7²+1=50. So 51 is wrong; it should be 50.',
  },
  {
    id: 'ssc-4',
    text: 'The ratio of ages of A and B is 3:5. After 10 years, the ratio becomes 5:7. What is the present age of A?',
    options: ['15 years', '20 years', '25 years', '10 years'],
    correct: '15 years',
    type: 'single',
    difficulty: 'medium',
    tags: ['ssc', 'quantitative-aptitude', 'ages'],
    explanation: 'Let A = 3x, B = 5x. After 10 years: (3x+10)/(5x+10) = 5/7 → 21x+70 = 25x+50 → 4x = 20 → x = 5. A = 15 years.',
  },
  {
    id: 'ssc-5',
    text: 'Which of the following is a synonym of "Erudite"?',
    options: ['Ignorant', 'Scholarly', 'Arrogant', 'Simple'],
    correct: 'Scholarly',
    type: 'single',
    difficulty: 'easy',
    tags: ['ssc', 'english', 'vocabulary', 'synonyms'],
    explanation: '"Erudite" means having or showing great knowledge or learning. "Scholarly" is its closest synonym.',
  },
  {
    id: 'ssc-6',
    text: 'A shopkeeper sells an article at 20% profit. If he had sold it for ₹40 more, the profit would have been 30%. The cost price is:',
    options: ['₹200', '₹300', '₹400', '₹500'],
    correct: '₹400',
    type: 'single',
    difficulty: 'hard',
    tags: ['ssc', 'quantitative-aptitude', 'profit-loss'],
    explanation: 'Let CP = x. At 20% profit: SP = 1.2x. At 30% profit: SP = 1.3x. Difference: 1.3x – 1.2x = 0.1x = 40 → x = 400.',
  },
  {
    id: 'ssc-7',
    text: 'Which gas is known as "Laughing Gas"?',
    options: ['Nitrogen Dioxide', 'Nitrous Oxide', 'Carbon Monoxide', 'Sulfur Dioxide'],
    correct: 'Nitrous Oxide',
    type: 'single',
    difficulty: 'easy',
    tags: ['ssc', 'science', 'chemistry', 'gk'],
    explanation: 'Nitrous Oxide (N₂O) is commonly called "Laughing Gas" because inhaling it can cause euphoria and laughter.',
  },
  {
    id: 'ssc-8',
    text: 'Select the correctly spelt word:',
    options: ['Accomodation', 'Accommodation', 'Acommodation', 'Acomodation'],
    correct: 'Accommodation',
    type: 'single',
    difficulty: 'easy',
    tags: ['ssc', 'english', 'spelling'],
    explanation: 'The correct spelling is "Accommodation" – with double \'c\' and double \'m\'.',
  },
  {
    id: 'ssc-9',
    text: 'The average of 5 numbers is 27. If one number is excluded, the average becomes 25. The excluded number is:',
    options: ['35', '37', '30', '25'],
    correct: '35',
    type: 'single',
    difficulty: 'medium',
    tags: ['ssc', 'quantitative-aptitude', 'average'],
    explanation: 'Sum of 5 numbers = 5 × 27 = 135. Sum of 4 numbers = 4 × 25 = 100. Excluded number = 135 – 100 = 35.',
  },
  {
    id: 'ssc-10',
    text: 'In a certain code, "FACE" is written as "HCEG". How is "KIND" written?',
    options: ['MKPF', 'NLOF', 'MKOF', 'MLFP'],
    correct: 'MKPF',
    type: 'single',
    difficulty: 'medium',
    tags: ['ssc', 'reasoning', 'coding-decoding'],
    explanation: 'Each letter is shifted 2 positions forward: F→H, A→C, C→E, E→G. So K→M, I→K, N→P, D→F = MKPF.',
  },
];

export const bankingQuestions: Question[] = [
  {
    id: 'bank-1',
    text: 'What does NBFC stand for in the Indian financial system?',
    options: [
      'National Banking and Finance Corporation',
      'Non-Banking Financial Company',
      'New Banking and Financial Cooperative',
      'National Bureau of Financial Compliance',
    ],
    correct: 'Non-Banking Financial Company',
    type: 'single',
    difficulty: 'easy',
    tags: ['banking', 'ibps', 'financial-awareness', 'nbfc'],
    explanation: 'NBFC stands for Non-Banking Financial Company. These are companies registered under the Companies Act that provide financial services but do not hold a banking license.',
  },
  {
    id: 'bank-2',
    text: 'The Monetary Policy Committee (MPC) of RBI is responsible for:',
    options: [
      'Regulating foreign exchange reserves',
      'Setting the repo rate and controlling inflation',
      'Supervising commercial banks',
      'Issuing government securities',
    ],
    correct: 'Setting the repo rate and controlling inflation',
    type: 'single',
    difficulty: 'medium',
    tags: ['banking', 'ibps', 'rbi', 'monetary-policy'],
    explanation: 'The MPC, established under the RBI Act, 1934, has the mandate of maintaining price stability (targeting 4% CPI inflation) while keeping the objective of growth in mind. It sets the policy repo rate.',
  },
  {
    id: 'bank-3',
    text: 'If Principal = ₹10,000, Rate = 10% p.a. compound interest, what is the amount after 2 years?',
    options: ['₹12,000', '₹12,100', '₹11,000', '₹12,200'],
    correct: '₹12,100',
    type: 'single',
    difficulty: 'easy',
    tags: ['banking', 'quantitative-aptitude', 'compound-interest'],
    explanation: 'A = P(1 + r/100)^n = 10000 × (1.1)² = 10000 × 1.21 = ₹12,100.',
  },
  {
    id: 'bank-4',
    text: 'Which of the following is NOT a function of the Reserve Bank of India?',
    options: [
      'Issue of currency notes',
      'Banker to the government',
      'Accepting deposits from the public',
      'Lender of last resort',
    ],
    correct: 'Accepting deposits from the public',
    type: 'single',
    difficulty: 'medium',
    tags: ['banking', 'ibps', 'rbi', 'functions'],
    explanation: 'RBI does not accept deposits from the general public — that is the function of commercial banks. RBI is a central bank, not a retail/commercial bank.',
  },
  {
    id: 'bank-5',
    text: 'The concept of "KYC" in banking primarily aims at:',
    options: [
      'Maximizing bank profits',
      'Preventing money laundering and fraud',
      'Offering better interest rates to customers',
      'Streamlining loan approvals',
    ],
    correct: 'Preventing money laundering and fraud',
    type: 'single',
    difficulty: 'easy',
    tags: ['banking', 'ibps', 'kyc', 'compliance'],
    explanation: 'KYC (Know Your Customer) is a mandatory process for banks to verify the identity of customers to prevent money laundering, terrorist financing, and other financial frauds.',
  },
  {
    id: 'bank-6',
    text: 'A passage with blank: "The bank ______ the loan application after verifying all documents." Choose the correct word:',
    options: ['sanctioned', 'sanctimonious', 'sanctuary', 'sanction'],
    correct: 'sanctioned',
    type: 'single',
    difficulty: 'easy',
    tags: ['banking', 'english', 'fill-in-the-blanks'],
    explanation: '"Sanctioned" (past tense of sanction) means officially approved or authorized, which fits in the context of a bank approving a loan.',
  },
  {
    id: 'bank-7',
    text: 'The Cash Reserve Ratio (CRR) is the percentage of deposits that banks must keep with:',
    options: ['Finance Ministry', 'Reserve Bank of India', 'State Bank of India', 'SEBI'],
    correct: 'Reserve Bank of India',
    type: 'single',
    difficulty: 'easy',
    tags: ['banking', 'ibps', 'crr', 'rbi'],
    explanation: 'CRR is the percentage of a bank\'s net demand and time liabilities (NDTL) that must be maintained with the RBI in the form of cash. It is a tool to control money supply.',
  },
  {
    id: 'bank-8',
    text: 'Directions: Choose the word which best expresses the meaning of "PRUDENT":',
    options: ['Reckless', 'Wise and careful', 'Generous', 'Timid'],
    correct: 'Wise and careful',
    type: 'single',
    difficulty: 'easy',
    tags: ['banking', 'english', 'vocabulary'],
    explanation: '"Prudent" means acting with or showing care and thought for the future. In banking, "prudent lending" means careful and responsible lending.',
  },
  {
    id: 'bank-9',
    text: 'A sum of money at simple interest amounts to ₹815 in 3 years and ₹854 in 4 years. The sum is:',
    options: ['₹650', '₹698', '₹700', '₹690'],
    correct: '₹698',
    type: 'single',
    difficulty: 'hard',
    tags: ['banking', 'quantitative-aptitude', 'simple-interest'],
    explanation: 'SI for 1 year = 854 – 815 = ₹39. SI for 3 years = 39 × 3 = ₹117. Principal = 815 – 117 = ₹698.',
  },
  {
    id: 'bank-10',
    text: 'SWIFT stands for:',
    options: [
      'Society for Worldwide Interbank Financial Telecommunication',
      'Standard World Interchange for Financial Transfers',
      'Secure Worldwide Internet Finance Technology',
      'System for Worldwide Interbank Fund Transfers',
    ],
    correct: 'Society for Worldwide Interbank Financial Telecommunication',
    type: 'single',
    difficulty: 'medium',
    tags: ['banking', 'ibps', 'financial-awareness'],
    explanation: 'SWIFT is a global member-owned cooperative and the world\'s leading provider of secure financial messaging services used for international money transfers between banks.',
  },
];

export const railwayQuestions: Question[] = [
  {
    id: 'rrb-1',
    text: 'Two trains of lengths 200m and 150m run on parallel tracks. When running in the same direction, the faster train crosses the slower one in 70 seconds. When running in opposite directions, they cross each other in 10 seconds. Find the speed of the faster train.',
    options: ['25 m/s', '30 m/s', '20 m/s', '35 m/s'],
    correct: '20 m/s',
    type: 'single',
    difficulty: 'hard',
    tags: ['railway', 'rrb', 'quantitative-aptitude', 'trains'],
    explanation: 'Total length = 350m. Let speeds be u (faster) and v (slower). Same direction: 350/(u–v) = 70 → u–v = 5. Opposite directions: 350/(u+v) = 10 → u+v = 35. Solving: 2u = 40 → u = 20 m/s, v = 15 m/s. Faster train speed = 20 m/s.',
  },
  {
    id: 'rrb-2',
    text: 'The Indian Railway zone "East Coast Railway" has its headquarters at:',
    options: ['Visakhapatnam', 'Bhubaneswar', 'Chennai', 'Kolkata'],
    correct: 'Bhubaneswar',
    type: 'single',
    difficulty: 'medium',
    tags: ['railway', 'rrb', 'gk', 'railway-zones'],
    explanation: 'East Coast Railway (ECoR), established in 2019, has its headquarters in Bhubaneswar, Odisha. It was carved out of South Eastern and East Central Railway zones.',
  },
  {
    id: 'rrb-3',
    text: 'Which is the longest railway platform in India?',
    options: ['Gorakhpur (UP)', 'Kollam (Kerala)', 'Kharagpur (WB)', 'Hubballi (Karnataka)'],
    correct: 'Hubballi (Karnataka)',
    type: 'single',
    difficulty: 'medium',
    tags: ['railway', 'rrb', 'gk', 'records'],
    explanation: 'Hubballi (formerly Hubli) railway station in Karnataka holds the record for the world\'s longest railway platform at 1,505 metres, surpassing Gorakhpur\'s 1,366 metres.',
  },
  {
    id: 'rrb-4',
    text: 'LCM of 12, 18 and 24 is:',
    options: ['36', '48', '72', '108'],
    correct: '72',
    type: 'single',
    difficulty: 'easy',
    tags: ['railway', 'rrb', 'quantitative-aptitude', 'lcm-hcf'],
    explanation: '12 = 2²×3, 18 = 2×3², 24 = 2³×3. LCM = 2³×3² = 8×9 = 72.',
  },
  {
    id: 'rrb-5',
    text: 'The term "Broad Gauge" in Indian Railways refers to a track width of:',
    options: ['1.000 m', '1.676 m', '0.762 m', '1.435 m'],
    correct: '1.676 m',
    type: 'single',
    difficulty: 'easy',
    tags: ['railway', 'rrb', 'gk', 'track-gauge'],
    explanation: 'Indian Broad Gauge (IBG) has a track width (gauge) of 1.676 metres (5 ft 6 in), which is wider than the standard gauge of 1.435 metres used in most countries.',
  },
  {
    id: 'rrb-6',
    text: 'A 240-litre mixture has milk and water in ratio 3:1. How much water must be added to make the ratio 3:2?',
    options: ['80 litres', '60 litres', '40 litres', '120 litres'],
    correct: '60 litres',
    type: 'single',
    difficulty: 'medium',
    tags: ['railway', 'rrb', 'quantitative-aptitude', 'mixtures'],
    explanation: 'Milk = (3/4) × 240 = 180 L, Water = 60 L. Milk stays constant at 180 L. For ratio 3:2: water needed = (2/3) × 180 = 120 L. Additional water = 120 – 60 = 60 litres.',
  },
  {
    id: 'rrb-7',
    text: 'Which of the following is the correct passive voice of: "The manager announced the results"?',
    options: [
      'The results were announced by the manager.',
      'The results are announced by the manager.',
      'The results had been announced by the manager.',
      'The manager was announcing the results.',
    ],
    correct: 'The results were announced by the manager.',
    type: 'single',
    difficulty: 'easy',
    tags: ['railway', 'rrb', 'english', 'grammar'],
    explanation: 'Simple Past Active → Simple Past Passive. "The manager announced" → "The results were announced by the manager."',
  },
  {
    id: 'rrb-8',
    text: 'India\'s first bullet train corridor is being built between:',
    options: [
      'Delhi – Agra',
      'Mumbai – Ahmedabad',
      'Chennai – Bangalore',
      'Pune – Mumbai',
    ],
    correct: 'Mumbai – Ahmedabad',
    type: 'single',
    difficulty: 'easy',
    tags: ['railway', 'rrb', 'current-affairs', 'bullet-train'],
    explanation: 'India\'s first High-Speed Rail (HSR) corridor is the Mumbai–Ahmedabad High Speed Rail (MAHSR) project, being developed with Japanese collaboration and using Shinkansen technology.',
  },
  {
    id: 'rrb-9',
    text: 'If 6 men can do a piece of work in 12 days, how many days will 8 men take to complete the same work?',
    options: ['9 days', '8 days', '10 days', '6 days'],
    correct: '9 days',
    type: 'single',
    difficulty: 'easy',
    tags: ['railway', 'rrb', 'quantitative-aptitude', 'work-time'],
    explanation: 'Total work = 6 × 12 = 72 man-days. Days for 8 men = 72 / 8 = 9 days.',
  },
  {
    id: 'rrb-10',
    text: 'The "Vande Bharat Express" is a:',
    options: [
      'Diesel-electric locomotive',
      'Self-propelled semi-high-speed electric multiple unit',
      'Steam locomotive for heritage routes',
      'Hydrogen fuel cell train',
    ],
    correct: 'Self-propelled semi-high-speed electric multiple unit',
    type: 'single',
    difficulty: 'medium',
    tags: ['railway', 'rrb', 'gk', 'trains'],
    explanation: 'Vande Bharat Express (Train 18) is a semi-high-speed, self-propelled (no separate locomotive) Electric Multiple Unit (EMU) train designed and manufactured in India under the Make in India initiative.',
  },
];

export const neetQuestions: Question[] = [
  {
    id: 'neet-1',
    text: 'Which of the following is the correct sequence of events in synaptic transmission?',
    options: [
      'Action potential → Ca²⁺ influx → vesicle fusion → neurotransmitter release',
      'Neurotransmitter release → Ca²⁺ influx → action potential → vesicle fusion',
      'Ca²⁺ influx → action potential → neurotransmitter release → vesicle fusion',
      'Vesicle fusion → action potential → Ca²⁺ influx → neurotransmitter release',
    ],
    correct: 'Action potential → Ca²⁺ influx → vesicle fusion → neurotransmitter release',
    type: 'single',
    difficulty: 'hard',
    tags: ['neet', 'biology', 'neuroscience', 'synaptic-transmission'],
    explanation: 'Action potential arrives at axon terminal → voltage-gated Ca²⁺ channels open → Ca²⁺ influx → synaptic vesicles fuse with pre-synaptic membrane → neurotransmitter released into synapse.',
  },
  {
    id: 'neet-2',
    text: 'The equation PV = nRT is known as the:',
    options: ['Boyle\'s Law', 'Charles\' Law', 'Ideal Gas Law', 'Dalton\'s Law'],
    correct: 'Ideal Gas Law',
    type: 'single',
    difficulty: 'easy',
    tags: ['neet', 'chemistry', 'gases', 'thermodynamics'],
    explanation: 'PV = nRT is the Ideal Gas Law where P = pressure, V = volume, n = moles, R = universal gas constant (8.314 J/mol·K), T = temperature in Kelvin.',
  },
  {
    id: 'neet-3',
    text: 'Which DNA repair mechanism removes thymine dimers caused by UV radiation?',
    options: ['Mismatch repair', 'Base excision repair', 'Nucleotide excision repair', 'Homologous recombination'],
    correct: 'Nucleotide excision repair',
    type: 'single',
    difficulty: 'hard',
    tags: ['neet', 'biology', 'genetics', 'dna-repair'],
    explanation: 'Nucleotide Excision Repair (NER) recognizes bulky DNA lesions like thymine dimers (caused by UV) and removes a stretch of ~25–30 nucleotides containing the damage, then fills the gap using the complementary strand.',
  },
  {
    id: 'neet-4',
    text: 'Hybridization of carbon in ethyne (C₂H₂) is:',
    options: ['sp³', 'sp²', 'sp', 'sp³d'],
    correct: 'sp',
    type: 'single',
    difficulty: 'easy',
    tags: ['neet', 'chemistry', 'organic-chemistry', 'hybridization'],
    explanation: 'Ethyne (H–C≡C–H) has a triple bond between carbons. Each carbon forms 2 sigma bonds (one with H, one with the other C) and 2 pi bonds. This gives sp hybridization (linear geometry, 180° bond angle).',
    trick: 'Triple bond = sp, Double bond = sp², Single bond = sp³',
  },
  {
    id: 'neet-5',
    text: 'Which of the following is NOT a feature of C4 plants?',
    options: [
      'Bundle sheath cells contain chloroplasts',
      'CO₂ is fixed first into oxaloacetate',
      'RuBisCO is present in mesophyll cells',
      'They show Kranz anatomy',
    ],
    correct: 'RuBisCO is present in mesophyll cells',
    type: 'single',
    difficulty: 'hard',
    tags: ['neet', 'biology', 'photosynthesis', 'c4-plants'],
    explanation: 'In C4 plants, RuBisCO is present in bundle sheath cells (not mesophyll cells). In mesophyll cells, PEP carboxylase fixes CO₂ into OAA (C4 compound), which is then transported to bundle sheath cells for the Calvin cycle.',
  },
  {
    id: 'neet-6',
    text: 'Which enzyme is responsible for unwinding the DNA double helix during replication?',
    options: ['DNA Polymerase III', 'Primase', 'Helicase', 'Ligase'],
    correct: 'Helicase',
    type: 'single',
    difficulty: 'easy',
    tags: ['neet', 'biology', 'molecular-biology', 'dna-replication'],
    explanation: 'Helicase unwinds and separates the two strands of the DNA double helix at the replication fork by breaking the hydrogen bonds between complementary base pairs.',
  },
  {
    id: 'neet-7',
    text: 'The quantum number that determines the shape of an orbital is the:',
    options: [
      'Principal quantum number (n)',
      'Azimuthal quantum number (l)',
      'Magnetic quantum number (m)',
      'Spin quantum number (s)',
    ],
    correct: 'Azimuthal quantum number (l)',
    type: 'single',
    difficulty: 'medium',
    tags: ['neet', 'chemistry', 'atomic-structure', 'quantum-numbers'],
    explanation: 'The azimuthal (or angular momentum) quantum number (l) determines the shape of the orbital. l = 0 → s (spherical), l = 1 → p (dumbbell), l = 2 → d, l = 3 → f.',
  },
  {
    id: 'neet-8',
    text: 'The tidal volume of a healthy adult at rest is approximately:',
    options: ['150 mL', '500 mL', '1200 mL', '3500 mL'],
    correct: '500 mL',
    type: 'single',
    difficulty: 'easy',
    tags: ['neet', 'biology', 'physiology', 'respiratory-system'],
    explanation: 'Tidal Volume (TV) is the volume of air inhaled or exhaled in each normal breath at rest — approximately 500 mL (0.5 L) in a healthy adult.',
  },
  {
    id: 'neet-9',
    text: 'Which of the following is an example of convergent evolution?',
    options: [
      'Forelimbs of humans and bats',
      'Wings of birds and insects',
      'Eyes of vertebrates and cephalopods',
      'Both B and C',
    ],
    correct: 'Both B and C',
    type: 'single',
    difficulty: 'hard',
    tags: ['neet', 'biology', 'evolution', 'convergent-evolution'],
    explanation: 'Convergent evolution occurs when unrelated organisms independently evolve similar traits. Wings of birds (vertebrates) and insects (arthropods), and the camera-type eyes of vertebrates and cephalopods (like octopus) are classic examples. Forelimbs of humans and bats are homologous structures (divergent evolution).',
  },
  {
    id: 'neet-10',
    text: 'In the SN2 mechanism, the rate of reaction depends on:',
    options: [
      'Concentration of substrate only',
      'Concentration of nucleophile only',
      'Both substrate and nucleophile concentration',
      'Neither substrate nor nucleophile concentration',
    ],
    correct: 'Both substrate and nucleophile concentration',
    type: 'single',
    difficulty: 'medium',
    tags: ['neet', 'chemistry', 'organic-chemistry', 'reaction-mechanisms'],
    explanation: 'SN2 (Substitution Nucleophilic Bimolecular) is a second-order reaction. Rate = k[substrate][nucleophile]. It involves a one-step mechanism with backside attack and inversion of configuration (Walden inversion).',
  },
];

export const jeeQuestions: Question[] = [
  {
    id: 'jee-1',
    text: 'A particle moves in a straight line with acceleration a = (3t² – 2t) m/s². If initial velocity = 2 m/s, what is the velocity at t = 2s?',
    options: ['10 m/s', '8 m/s', '6 m/s', '12 m/s'],
    correct: '6 m/s',
    type: 'single',
    difficulty: 'hard',
    tags: ['jee', 'physics', 'kinematics', 'calculus'],
    explanation: 'v = u + ∫₀² a dt = 2 + ∫₀²(3t²–2t)dt. Integrating: [t³–t²]₀² = (8–4) – (0) = 4. So v = 2 + 4 = 6 m/s.',
  },
  {
    id: 'jee-2',
    text: 'The number of real roots of the equation x² + 5|x| + 6 = 0 is:',
    options: ['0', '2', '4', '1'],
    correct: '0',
    type: 'single',
    difficulty: 'medium',
    tags: ['jee', 'mathematics', 'quadratic-equations', 'algebra'],
    explanation: 'For x ≥ 0: x² + 5x + 6 = 0 → (x+2)(x+3) = 0 → x = –2 or –3 (both negative, rejected). For x < 0: x² – 5x + 6 = 0 → (x–2)(x–3) = 0 → x = 2 or 3 (both positive, rejected). So no real roots.',
  },
  {
    id: 'jee-3',
    text: 'Which of the following represents the correct order of first ionization energy?',
    options: ['Na < Mg < Al < Si', 'Na < Al < Mg < Si', 'Al < Na < Mg < Si', 'Si < Al < Mg < Na'],
    correct: 'Na < Al < Mg < Si',
    type: 'single',
    difficulty: 'hard',
    tags: ['jee', 'chemistry', 'periodic-table', 'ionization-energy'],
    explanation: 'Generally IE increases across a period, but there are exceptions. Al has lower IE than Mg (Al loses 3p electron more easily than Mg loses 3s). Order: Na(496) < Al(577) < Mg(738) < Si(786) kJ/mol.',
    trick: 'Exception: Mg > Al and P > S due to half-filled/full-filled stability.',
  },
  {
    id: 'jee-4',
    text: 'The electric field intensity at a point on the axis of an electric dipole at distance r (r >> d) from its centre is proportional to:',
    options: ['1/r', '1/r²', '1/r³', '1/r⁴'],
    correct: '1/r³',
    type: 'single',
    difficulty: 'medium',
    tags: ['jee', 'physics', 'electrostatics', 'electric-dipole'],
    explanation: 'For an electric dipole, E on axial position = 2kp/r³ and E on equatorial position = kp/r³, where p is dipole moment. Both vary as 1/r³ for r >> d.',
  },
  {
    id: 'jee-5',
    text: 'If |a⃗| = 3, |b⃗| = 4, and |a⃗ + b⃗| = 5, then |a⃗ × b⃗| = ?',
    options: ['12', '7', '25', '0'],
    correct: '12',
    type: 'single',
    difficulty: 'medium',
    tags: ['jee', 'mathematics', 'vectors', 'cross-product'],
    explanation: '|a⃗ + b⃗|² = |a⃗|² + |b⃗|² + 2a⃗·b⃗ → 25 = 9 + 16 + 2a⃗·b⃗ → a⃗·b⃗ = 0. So a⃗ ⊥ b⃗. |a⃗ × b⃗| = |a⃗||b⃗|sin(90°) = 3×4×1 = 12.',
  },
  {
    id: 'jee-6',
    text: 'The number of isomers of C₄H₈O₂ that are esters is:',
    options: ['3', '4', '5', '6'],
    correct: '4',
    type: 'single',
    difficulty: 'hard',
    tags: ['jee', 'chemistry', 'organic-chemistry', 'isomers'],
    explanation: 'Esters with formula C₄H₈O₂: Methyl propanoate, Ethyl acetate, Propyl formate, Isopropyl formate — 4 esters.',
  },
  {
    id: 'jee-7',
    text: 'A body is projected vertically upward with velocity u. The ratio of time of ascent to time of descent is:',
    options: ['1:2', '2:1', '1:1', 'depends on u'],
    correct: '1:1',
    type: 'single',
    difficulty: 'easy',
    tags: ['jee', 'physics', 'kinematics', 'projectile'],
    explanation: 'Time of ascent = u/g. Time of descent = u/g. Ratio = 1:1 (in absence of air resistance, time of ascent equals time of descent).',
  },
  {
    id: 'jee-8',
    text: 'Which of the following is an example of an SN1 reaction?',
    options: [
      'CH₃Br + OH⁻ in acetone',
      '(CH₃)₃CBr + H₂O in aqueous solution',
      'CH₃Cl + CN⁻ in DMSO',
      'CH₃CH₂Br + I⁻ in acetone',
    ],
    correct: '(CH₃)₃CBr + H₂O in aqueous solution',
    type: 'single',
    difficulty: 'medium',
    tags: ['jee', 'chemistry', 'organic-chemistry', 'reaction-mechanism'],
    explanation: 'SN1 reactions occur with tertiary carbocations in polar protic solvents. (CH₃)₃CBr (tertiary) + H₂O (polar protic) proceeds via a stable tertiary carbocation intermediate — classic SN1 conditions.',
  },
  {
    id: 'jee-9',
    text: 'The integral ∫₀^π sin(x) dx equals:',
    options: ['0', '1', '2', 'π'],
    correct: '2',
    type: 'single',
    difficulty: 'easy',
    tags: ['jee', 'mathematics', 'calculus', 'integration'],
    explanation: '∫₀^π sin(x) dx = [–cos(x)]₀^π = –cos(π) – (–cos(0)) = –(–1) – (–1) = 1 + 1 = 2.',
  },
  {
    id: 'jee-10',
    text: 'Young\'s double slit experiment: if the distance between slits is halved and distance from screen is doubled, the fringe width becomes:',
    options: ['Same', 'Doubled', '4 times', 'Halved'],
    correct: '4 times',
    type: 'single',
    difficulty: 'medium',
    tags: ['jee', 'physics', 'optics', 'interference'],
    explanation: 'Fringe width β = λD/d. If d → d/2 and D → 2D: β\' = λ(2D)/(d/2) = 4λD/d = 4β. Fringe width becomes 4 times.',
  },
];

export const currentAffairsQuestions: Question[] = [
  {
    id: 'ca-1',
    text: 'Which country hosted the G20 Summit in 2023?',
    options: ['Indonesia', 'India', 'Brazil', 'South Africa'],
    correct: 'India',
    type: 'single',
    difficulty: 'easy',
    tags: ['current-affairs', 'gk', 'g20', 'india'],
    explanation: 'India held the G20 Presidency in 2022-23 under the theme "Vasudhaiva Kutumbakam" (One Earth, One Family, One Future). The G20 Leaders\' Summit was held in New Delhi on September 9-10, 2023.',
  },
  {
    id: 'ca-2',
    text: 'The "PM Vishwakarma" scheme was launched to support:',
    options: [
      'Startup entrepreneurs',
      'Traditional artisans and craftspeople',
      'Agricultural farmers',
      'Digital tech workers',
    ],
    correct: 'Traditional artisans and craftspeople',
    type: 'single',
    difficulty: 'easy',
    tags: ['current-affairs', 'gk', 'government-schemes'],
    explanation: 'PM Vishwakarma Scheme (launched September 17, 2023) provides holistic support to traditional artisans and craftspeople engaged in 18 traditional trades, including financial assistance, skill training, and digital integration.',
  },
  {
    id: 'ca-3',
    text: 'Chandrayaan-3 successfully landed near the Moon\'s south pole in:',
    options: ['June 2023', 'July 2023', 'August 2023', 'September 2023'],
    correct: 'August 2023',
    type: 'single',
    difficulty: 'easy',
    tags: ['current-affairs', 'science-tech', 'isro', 'space'],
    explanation: 'India\'s Chandrayaan-3 mission successfully landed on the lunar south pole on August 23, 2023, making India the first country to achieve a soft landing near the Moon\'s south pole and the 4th country to land on the Moon.',
  },
  {
    id: 'ca-4',
    text: 'The "One Nation One Election" concept proposes:',
    options: [
      'A single voter ID for all states',
      'Simultaneous elections for Lok Sabha and all state assemblies',
      'Online voting across India',
      'Elections every 3 years instead of 5',
    ],
    correct: 'Simultaneous elections for Lok Sabha and all state assemblies',
    type: 'single',
    difficulty: 'medium',
    tags: ['current-affairs', 'polity', 'elections'],
    explanation: '"One Nation, One Election" proposes synchronizing elections for the Lok Sabha (Parliament) and all State Legislative Assemblies to be held simultaneously, to reduce election expenditure and governance disruption.',
  },
  {
    id: 'ca-5',
    text: 'India\'s first underwater metro rail service was inaugurated in which city?',
    options: ['Mumbai', 'Chennai', 'Kolkata', 'Delhi'],
    correct: 'Kolkata',
    type: 'single',
    difficulty: 'medium',
    tags: ['current-affairs', 'infrastructure', 'metro', 'india'],
    explanation: 'India\'s first underwater metro service was inaugurated in Kolkata in March 2024, running under the Hooghly River. This is part of the East-West Metro (Metro Rail Project) connecting Howrah Maidan and Esplanade.',
  },
];

// ─── Exam Cards Data ──────────────────────────────────────────────────────────

export const examCards: ExamCard[] = [
  {
    id: 'upsc',
    name: 'UPSC Civil Services',
    fullName: 'Union Public Service Commission – IAS/IPS/IFS',
    category: 'Central Government',
    icon: '🏛️',
    color: 'from-orange-500 to-red-600',
    description: 'The most prestigious exam in India for IAS, IPS, IFS officers. Covers History, Geography, Polity, Economy, Science & Technology.',
    vacancies: '1,100+ posts',
    examDate: 'May (Prelims)',
    difficulty: 'hard',
    topics: ['Indian History', 'Indian Polity', 'Geography', 'Economics', 'Science & Technology', 'Current Affairs', 'Ethics'],
    sessionId: 'upsc-session',
    questionCount: upscQuestions.length,
  },
  {
    id: 'ssc-cgl',
    name: 'SSC CGL',
    fullName: 'Staff Selection Commission – Combined Graduate Level',
    category: 'Central Government',
    icon: '📋',
    color: 'from-blue-500 to-indigo-600',
    description: 'Combined Graduate Level exam for Grade B and C posts. Tests Reasoning, Quantitative Aptitude, English, and General Awareness.',
    vacancies: '17,000+ posts',
    examDate: 'Multiple sessions',
    difficulty: 'medium',
    topics: ['Quantitative Aptitude', 'General Intelligence & Reasoning', 'English Language', 'General Awareness', 'Statistics'],
    sessionId: 'ssc-session',
    questionCount: sscQuestions.length,
  },
  {
    id: 'ibps-po',
    name: 'IBPS PO',
    fullName: 'Institute of Banking Personnel Selection – Probationary Officer',
    category: 'Banking',
    icon: '🏦',
    color: 'from-green-500 to-teal-600',
    description: 'Bank PO exam for Probationary Officer posts in PSU banks. Covers Reasoning, Quantitative Aptitude, English, General Awareness & Banking.',
    vacancies: '4,000+ posts',
    examDate: 'October–November',
    difficulty: 'medium',
    topics: ['Reasoning Ability', 'Quantitative Aptitude', 'English Language', 'General Awareness', 'Computer Aptitude'],
    sessionId: 'banking-session',
    questionCount: bankingQuestions.length,
  },
  {
    id: 'rrb-ntpc',
    name: 'RRB NTPC',
    fullName: 'Railway Recruitment Board – Non-Technical Popular Categories',
    category: 'Railway',
    icon: '🚆',
    color: 'from-purple-500 to-pink-600',
    description: 'Railway exam for NTPC posts including Junior Clerk, Station Master, Goods Guard and more. Covers Maths, Reasoning, and General Awareness.',
    vacancies: '11,000+ posts',
    examDate: 'Throughout the year',
    difficulty: 'medium',
    topics: ['Mathematics', 'General Intelligence & Reasoning', 'General Awareness', 'English Language'],
    sessionId: 'railway-session',
    questionCount: railwayQuestions.length,
  },
  {
    id: 'neet',
    name: 'NEET UG',
    fullName: 'National Eligibility cum Entrance Test – Undergraduate',
    category: 'Medical',
    icon: '⚕️',
    color: 'from-red-500 to-pink-600',
    description: 'National medical entrance exam for MBBS and BDS admissions in India. Covers Physics, Chemistry, and Biology at Class 11–12 level.',
    vacancies: '1,00,000+ MBBS seats',
    examDate: 'May',
    difficulty: 'hard',
    topics: ['Physics', 'Chemistry', 'Botany', 'Zoology'],
    sessionId: 'neet-session',
    questionCount: neetQuestions.length,
  },
  {
    id: 'jee-main',
    name: 'JEE Main',
    fullName: 'Joint Entrance Examination – Main',
    category: 'Engineering',
    icon: '⚙️',
    color: 'from-yellow-500 to-orange-600',
    description: 'Gateway to NITs, IIITs, and other engineering colleges. Tests Physics, Chemistry, and Mathematics at advanced level.',
    vacancies: '30,000+ NIT/IIIT seats',
    examDate: 'January & April',
    difficulty: 'hard',
    topics: ['Physics', 'Chemistry', 'Mathematics'],
    sessionId: 'jee-session',
    questionCount: jeeQuestions.length,
  },
  {
    id: 'cat',
    name: 'CAT',
    fullName: 'Common Admission Test – IIM MBA Entrance',
    category: 'Management',
    icon: '📊',
    color: 'from-indigo-500 to-blue-700',
    description: 'Premier MBA entrance test for IIMs and top B-schools. Tests Verbal Ability, Data Interpretation & Logical Reasoning, and Quantitative Ability.',
    vacancies: '5,000+ IIM seats',
    examDate: 'November',
    difficulty: 'hard',
    topics: ['Verbal Ability & RC', 'Data Interpretation', 'Logical Reasoning', 'Quantitative Ability'],
    sessionId: 'ssc-session',
    questionCount: sscQuestions.length,
  },
  {
    id: 'current-affairs',
    name: 'Current Affairs GK',
    fullName: 'Current Affairs & General Knowledge – All Exams',
    category: 'General',
    icon: '📰',
    color: 'from-cyan-500 to-blue-600',
    description: 'Stay updated with the latest current affairs, government schemes, sports, awards, and national/international events for all competitive exams.',
    vacancies: 'All Exams',
    examDate: 'Ongoing',
    difficulty: 'easy',
    topics: ['National Events', 'International Affairs', 'Government Schemes', 'Awards & Honours', 'Sports', 'Science & Technology'],
    sessionId: 'ca-session',
    questionCount: currentAffairsQuestions.length,
  },
  {
    id: 'nda',
    name: 'NDA',
    fullName: 'National Defence Academy – Army/Navy/Air Force',
    category: 'Defence',
    icon: '🎖️',
    color: 'from-gray-600 to-gray-800',
    description: 'National Defence Academy entrance exam for 10+2 passed candidates to join Indian Army, Navy and Air Force as officers.',
    vacancies: '400+ posts per year',
    examDate: 'April & September',
    difficulty: 'medium',
    topics: ['Mathematics', 'General Ability Test', 'Physics', 'Chemistry', 'History', 'English'],
    sessionId: 'session-demo-1',
    questionCount: mockQuestions.length,
  },
  {
    id: 'clat',
    name: 'CLAT',
    fullName: 'Common Law Admission Test – National Law Universities',
    category: 'Law',
    icon: '⚖️',
    color: 'from-amber-500 to-yellow-600',
    description: 'Common entrance test for admission to undergraduate and postgraduate law programs at the 24 National Law Universities (NLUs) of India.',
    vacancies: '3,500+ NLU seats',
    examDate: 'December',
    difficulty: 'medium',
    topics: ['English Language', 'Current Affairs & GK', 'Legal Reasoning', 'Logical Reasoning', 'Quantitative Techniques'],
    sessionId: 'ca-session',
    questionCount: currentAffairsQuestions.length,
  },
];

// ─── Exam Session Map ─────────────────────────────────────────────────────────

export const examSessionQuestions: Record<string, Question[]> = {
  'upsc-session': upscQuestions,
  'ssc-session': sscQuestions,
  'banking-session': bankingQuestions,
  'railway-session': railwayQuestions,
  'neet-session': neetQuestions,
  'jee-session': jeeQuestions,
  'ca-session': currentAffairsQuestions,
  'session-demo-1': mockQuestions.slice(0, 10),
};

// ─── Resource Links ───────────────────────────────────────────────────────────

export const resourceLinks: ResourceLink[] = [
  {
    id: 'gktoday',
    name: 'GKToday',
    description: 'Daily current affairs, GK questions, and topic-wise MCQs for UPSC, SSC, Banking, and all competitive exams. Updated every day.',
    url: 'https://www.gktoday.in',
    icon: '📰',
    category: 'Current Affairs & GK',
    features: ['Daily Current Affairs', 'Topic-wise MCQs', 'GK Question Banks', 'Exam-specific Quizzes'],
    color: 'from-blue-500 to-cyan-600',
    badge: 'Free',
  },
  {
    id: 'oliveboard',
    name: 'Oliveboard',
    description: 'Previous year question papers, free mock tests, and sectional tests for Banking, SSC, Railways, and government exams.',
    url: 'https://www.oliveboard.in',
    icon: '📝',
    category: 'Mock Tests & PYQs',
    features: ['Previous Year Papers', 'Full Mock Tests', 'Topic Tests', 'Video Solutions'],
    color: 'from-orange-500 to-red-500',
    badge: 'Free & Paid',
  },
  {
    id: 'practicemock',
    name: 'PracticeMock',
    description: 'AI-powered mock tests for all government exams with detailed analytics. Covers IBPS, SBI, SSC, RRB, UPSC, and more.',
    url: 'https://www.practicemock.com',
    icon: '🎯',
    category: 'Mock Tests',
    features: ['AI-Adaptive Tests', 'All Govt Exams', 'Performance Analytics', 'Topic-wise Practice'],
    color: 'from-purple-500 to-indigo-600',
    badge: 'Free & Paid',
  },
  {
    id: 'testbook',
    name: 'Testbook',
    description: 'Comprehensive test series for 250+ government exams. Live classes, study notes, and detailed mock tests with solutions.',
    url: 'https://testbook.com',
    icon: '📚',
    category: 'Test Series',
    features: ['Live Classes', 'Test Series', 'Study Notes', 'Bilingual Content'],
    color: 'from-green-500 to-teal-600',
    badge: 'Free & Paid',
  },
  {
    id: 'adda247',
    name: 'Adda247',
    description: 'India\'s leading exam preparation platform with study material, video lectures, quizzes, and books for government exams.',
    url: 'https://www.adda247.com',
    icon: '🏆',
    category: 'Study Material',
    features: ['Video Lectures', 'PDF Notes', 'Daily Quizzes', 'Banking & SSC Focus'],
    color: 'from-yellow-500 to-orange-500',
    badge: 'Free & Paid',
  },
  {
    id: 'unacademy',
    name: 'Unacademy',
    description: 'India\'s largest online learning platform with live classes by top educators for UPSC, JEE, NEET, SSC, Banking, and more.',
    url: 'https://unacademy.com',
    icon: '🎓',
    category: 'Live Classes',
    features: ['Live Classes', 'Recorded Lectures', 'Doubt Sessions', 'All Major Exams'],
    color: 'from-red-500 to-pink-600',
    badge: 'Free & Paid',
  },
  {
    id: 'byju',
    name: 'BYJU\'S Exam Prep',
    description: 'Comprehensive exam preparation with video lessons, mock tests, and live classes for IAS, JEE, NEET, SSC, Banking and more.',
    url: 'https://byjusexamprep.com',
    icon: '✏️',
    category: 'Comprehensive Prep',
    features: ['Smart Learning', 'Live Tests', 'Study Planner', 'Expert Mentors'],
    color: 'from-indigo-500 to-purple-600',
    badge: 'Free & Paid',
  },
  {
    id: 'drishti-ias',
    name: 'Drishti IAS',
    description: 'Most trusted UPSC preparation platform with comprehensive study material, current affairs magazine, and mock tests for Civil Services.',
    url: 'https://www.drishtiias.com',
    icon: '🏛️',
    category: 'UPSC Focused',
    features: ['UPSC Study Material', 'Current Affairs Magazine', 'Mains Answer Writing', 'Hindi Medium Content'],
    color: 'from-slate-600 to-slate-800',
    badge: 'Free & Paid',
  },
];
